### ISSUE TITLE
"CANNOT ADD DUPLICATE PIPE NBT" in logs

### ISSUE THREAD

**Issue by huanqiugame** [AViewFromTheTop/SimpleCopperPipesMC#12]
Hi! I'm a Minecraft player from China. The following words might have grammar mistakes, and hope you understand. Thanks.

# Description

I built a machine (made by 肥啾 on Bilibili) to get string, using some features from tripwire hook. More details are from [here](https://www.bilibili.com/read/cv18551694) (Chinese page, you may have to use a translator). Anyway, when I built it in my world with some hoppers and pipes, a message of "CANNOT ADD DUPLICATE PIPE NBT" immediately fill the log. It uses CPU resources and make the value of MSPT very large. I tested in only 2 mods (Fabric API and Simple Copper Pipes mod) and confirmed. Here are the screenshot and the log file.

![2023-01-03_21 53 26](https://user-images.githubusercontent.com/85951426/210371089-b1513e9e-58e2-42b8-93da-8c481f4a3b13.png)
[2023-01-03-6.log](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/files/10337089/2023-01-03-6.log)

*With [XeKr redstone display resource pack](https://www.curseforge.com/minecraft/texture-packs/xekr-redstone-display)*

However, the pipes still work well though the keep sending errors. So maybe you just delete a line of code to fix that.

# More details

Client:
- OS: macOS 13.1
- Java: OpenJDK 17.0.2, 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing) aarch64
- CPU & GPU: Apple M1

Server:
- OS: Windows 10 22H2 19045.2364
- Java: 18.0.2 Java HotSpot 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing) x86_64
- CPU: Intel Core i3-3240 @ 3.40GHz
- GPU: NVIDIA GeForce GT 710
- RAM: 12.0GB DDR3

Actually, the bug was first found on the Server PC, and confirmed on the Client Mac, so there shouldn't be OS' problems.

**Comment by AViewFromTheTop** [comment]
I will look into it.
Thank you for reporting this issue!

**Comment by RainbowFishNetwork** [comment]
I have the same issue when I upgrade my server from 1.18.2 to 1.19.2

**Comment by AViewFromTheTop** [comment]
Fixed in 1.12!
