### ISSUE TITLE
Smoking pipes do not calm bees. Smoke particles are seen, but no effect. - 1.19.3

### ISSUE THREAD

**Issue by WildBanjos** [AViewFromTheTop/SimpleCopperPipesMC#15]
Tested on clean install. Regardless of configuration, smoking pipes do not seem to calm bees. In all tested configurations, the smoke particle effect is seen, but does not make any effect to the bees, they still become angry when harvesting. According to the description, the smoking pipe only needs to be under the beehive/beehouse.

The attached images show which configurations were tested. It was also tested by replacing the top right corner pipe with a copper fitting.

![2](https://user-images.githubusercontent.com/117058715/227402202-6d582b53-d0e5-491a-bee0-cecb365a06b2.jpg)
![1](https://user-images.githubusercontent.com/117058715/227402205-eb584d7f-25ec-4ade-a3cc-74a2b16681db.jpg)
![8](https://user-images.githubusercontent.com/117058715/227402235-f7265451-041e-4e28-ab2a-8c236be6550b.jpg)
![7](https://user-images.githubusercontent.com/117058715/227402236-272fec9a-0678-4316-baca-c9ab825fc338.jpg)
![6](https://user-images.githubusercontent.com/117058715/227402240-9633a5c0-7969-4878-ba8e-d0f5dff23a0a.jpg)
![5](https://user-images.githubusercontent.com/117058715/227402244-23e5a6a9-8095-4499-ae5f-706c055454bd.jpg)
![4](https://user-images.githubusercontent.com/117058715/227402245-19042a22-6aaf-45ae-bf2c-652a78a70d5b.jpg)
![3](https://user-images.githubusercontent.com/117058715/227402249-66a7e2b7-3b99-48a6-8818-7a373c4a43c1.jpg)

**Comment by AViewFromTheTop** [comment]
I haven’t been able to reproduce this in the latest release. What mods are you using?

**Comment by WildBanjos** [comment]
So, my initial test did have 48 mods in that instance. However, I reran the same test using a minimal mod list below:

`fabric-api-0.73.0+1.19.3
indium-1.0.12+mc1.19.3
lithium-fabric-mc1.19.3-0.10.4
lunade-copper-pipe-1.12-1.19.3
sodium-fabric-mc1.19.3-0.4.8+build.22`

This led to the same behavior as mentioned above. Bees attacked regardless.

However, I saw there was a new release in **may** since the issue was created, I retested and it seems the issue was resolved. Bees behave as expected and do not attack if smoke is coming from a pipe. I can close the issue.

**Comment by AViewFromTheTop** [comment]
> However, I saw there was a new release in **May** since the issue was created, I retested and it seems the issue was resolved. Bees behave as expected and do not attack if smoke is coming from a pipe. I can close the issue.

Alright, I'm glad to hear that! I probably screwed up a mixin at some point and didn't realize, I've gone back and cleaned them up in the time since you opened this issue.
