### ISSUE TITLE
[BUG] The copper pipe is reversely connected to the shulker box to place items into the Shulker box.

### ISSUE THREAD

**Issue by Qian-F** [AViewFromTheTop/SimpleCopperPipesMC#16]
https://github.com/Qian-F/QFserver-Wonder/assets/99337738/f9919126-61f1-4916-bfcb-3a39385001c9

**Comment by Qian-F** [comment]
此模组疑似停更，该问题还有可能成为遗留问题，请求玩家社区帮助

**Comment by Qian-F** [comment]
@AViewFromTheTop check this issue plz

**Comment by AViewFromTheTop** [comment]
I don’t see an issue with this.
The side of the pipe with the “lip” on it is the side that the pipe pushes items towards.

**Comment by Qian-F** [comment]
> I don’t see an issue with this. The side of the pipe with the “lip” on it is the side that the pipe pushes items towards.

But this leads to shulker boxes being able to nest Shulker boxes. I don't think that's allowed.

**Comment by AViewFromTheTop** [comment]
> > I don’t see an issue with this. The side of the pipe with the “lip” on it is the side that the pipe pushes items towards.
> 
> But this leads to shulker boxes being able to nest Shulker boxes. I don't think that's allowed.

OH.
Ok, *thats* the issue, I somehow hadn’t realized.
I’ll reopen this issue, thank you!

**Comment by Qian-F** [comment]
> > > I don’t see an issue with this. The side of the pipe with the “lip” on it is the side that the pipe pushes items towards.
> > 
> > But this leads to shulker boxes being able to nest Shulker boxes. I don't think that's allowed.
> 
> OH.
> Ok, *thats* the issue, I somehow hadn’t realized.
> I’ll reopen this issue, thank you!

Hopefully you can fix this soon, maybe by adding a judgment between the copper tube and shulker box, can you release a fix for 1.18.2?

**Comment by Qian-F** [comment]
> > > I don’t see an issue with this. The side of the pipe with the “lip” on it is the side that the pipe pushes items towards.
> > 
> > 
> > But this leads to shulker boxes being able to nest Shulker boxes. I don't think that's allowed.
> 
> OH. Ok, _thats_ the issue, I somehow hadn’t realized. I’ll reopen this issue, thank you!

@AViewFromTheTop  

I'm sorry to bother you again. Can you give me an approximate time to fix this bug? Since it depends on whether I should add it to my server, this vulnerability can cause a lot of problems.

**Comment by AViewFromTheTop** [comment]
I've just fixed it for 1.20, I will release fixes for older versions soon.

**Comment by QianFuv** [comment]
> I've just fixed it for 1.20, I will release fixes for older versions soon.

Thank you for your efforts! Thank you so much!!
