### ISSUE TITLE
[ BUG ] Item transport problem

### ISSUE THREAD

**Issue by QianFuv** [AViewFromTheTop/SimpleCopperPipesMC#17]
Yeah, it's me again
After the last fix update, more serious bugs came
See the details in the video I uploaded to youtube (These bugs are hard for me to put into words)

https://youtu.be/ksG1o7p7Xv4

**Comment by QianFuv** [comment]
@AViewFromTheTop

**Comment by QianFuv** [comment]
It is worth noting that I only tested on fabric1.18.2, not the other versions.

**Comment by AViewFromTheTop** [comment]
dangit.

**Comment by QianFuv** [comment]
I won't continue to track this issue, but hope you can fix it anyway.

**Comment by AViewFromTheTop** [comment]
hey, im sorry for not responding
i have been very stressed recently, but i finally was able to fix all issues on 1.20.
im not sure if i will fix or update 1.18/1.19 anymore, as i have many other projects and responsibilities in my personal life to take care of. however, 1.20 is guaranteed to work perfectly!

**Comment by QianFuv** [comment]
That's fine! thank you for your effort :)
