### ISSUE TITLE
Reverting a pipe's oxidization stage by alt-clicking doesn't fully work on servers

### ISSUE THREAD

**Issue by EthanRStokes** [AViewFromTheTop/SimpleCopperPipesMC#19]
on servers, alt clicking the pipe (or fitting) with an axe does revert the oxidization, but it's missing the particles and the sound
but i noticed that it still does work when another player does it

**Comment by EthanRStokes** [comment]
is this fixed in 1.13.4?

**Comment by AViewFromTheTop** [comment]
> is this fixed in 1.13.4?

No
1.13.4 fixes a critical issue with Pipes either not transporting items half of the time, or constantly transporting items from slots they aren’t supposed to

**Comment by EthanRStokes** [comment]
figured out this also happens in singleplayer
