### ISSUE TITLE
copper pipes really broken

### ISSUE THREAD

**Issue by EthanRStokes** [AViewFromTheTop/SimpleCopperPipesMC#21]
copper pipes oriented like this or similar just have stopped working in recent updates
they just dont transfer items
![image](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/assets/39657565/85408526-c2e7-48f3-969f-fbe494fe1d00)

**Comment by AViewFromTheTop** [comment]
> copper pipes oriented like this or similar just have stopped working in recent updates
> they just dont transfer items
> ![image](https://user-images.githubusercontent.com/39657565/266156560-85408526-c2e7-48f3-969f-fbe494fe1d00.png)

Are you serious

**Comment by AViewFromTheTop** [comment]
![2023-09-06_22 37 32](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/assets/87103914/4a3436f4-aa4e-4f67-91cf-88318dd810d3)
@Treetrain1 its working fine for me
are you on the latest version
