### ISSUE TITLE
Conflict with Create Filters [Fabric 1.20.1]

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [AViewFromTheTop/SimpleCopperPipesMC#24]
When enabled with the Create Mod, in the [Landscapes Reimagined](https://modrinth.com/modpack/landscapes-reimagined) modpack, I have noticed that this mod stops you from opening either of the two create filters. The only issue in the log that pops up is this:

[16:58:01] [Render thread/ERROR]: ########## GL ERROR ##########
[16:58:01] [Render thread/ERROR]: @ Pre render
[16:58:01] [Render thread/ERROR]: 65539: Invalid key -1

Here is the whole log if there is anything else I am missing: [log here](https://mclo.gs/c86u77W)
Also wanted to note I went through all the mods in this pack and narrowed it down to this mod.

**Comment by vivagabe** [comment]
Can confirm this issue still exist on the latest version.

**Comment by AViewFromTheTop** [comment]
Just to be sure, is that the little portable thing you can open a GUI with?
If so, this is a @Treetrain1 issue and 100% links back to FrozenLib- not WW nor SCP on their own.

**Comment by AViewFromTheTop** [comment]
Yep.
https://github.com/FrozenBlock/WilderWild/issues/318.
@Treetrain1 it's a FrozenLib issue.

**Comment by EthanRStokes** [comment]
> Just to be sure, is that the little portable thing you can open a GUI with?
> 
> If so, this is a @Treetrain1 issue and 100% links back to FrozenLib- not WW nor SCP on their own.

Yeah definitely FrozenLib

**Comment by AViewFromTheTop** [comment]
Just fixed thanks to Treetrain1, should be up on Modrinth now and CF soon.
