### ISSUE TITLE
Item transfer crashing

### ISSUE THREAD

**Issue by voidahoy** [AViewFromTheTop/SimpleCopperPipesMC#25]
Almost every time you insert only 1 singular item into a chest connected to copper pipes, the game crashes.

**Comment by voidahoy** [comment]
I'm on 1.20.1, I assume this is fixed in future versions but I am running a modpack for myself on 1.20.1 so I am unable to move to 1.20.2. If you could please release a fix for 1.20.1 I would be very grateful.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 since you did the transfer api stuff do you have any clue why this would happen?

**Comment by AViewFromTheTop** [comment]
Would you be able to share logs?

**Comment by EthanRStokes** [comment]
> @Treetrain1 since you did the transfer api stuff do you have any clue why this would happen?

I have no clue without a form of context or logs

**Comment by voidahoy** [comment]
Sorry! I completely forgot to upload crash logs, here it is.
[crash-2023-11-01_15.29.08-client.txt](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/files/13232323/crash-2023-11-01_15.29.08-client.txt)

**Comment by EthanRStokes** [comment]
Seems to be an issue with Smooth Swapping

**Comment by voidahoy** [comment]
Thank you so much! That fixed it!
