### ISSUE TITLE
Server crashes due to DataFixers

### ISSUE THREAD

**Issue by ExDrill** [AViewFromTheTop/SimpleCopperPipesMC#42]
https://pastebin.com/zYrqcRWt

This issue only happened when a bunch of chunks were being loaded at once and the server was being overloaded. This only stopped when I removed Simple Copper Pipes.

**Comment by AViewFromTheTop** [comment]
> https://pastebin.com/zYrqcRWt
> 
> This issue only happened when a bunch of chunks were being loaded at once and the server was being overloaded. This only stopped when I removed Simple Copper Pipes.

Lucky you, being on 1.21.1!
It's likely a FrozenLib issue that I already fixed, but me and Liukrast are working on making it multiloader.
Once that's finished I'll update pipes and you shouldn't have the issue anymore.

**Comment by ExDrill** [comment]
Thanks! Is there any ETA to when this could be happening?

**Comment by AViewFromTheTop** [comment]
> Thanks! Is there any ETA to when this could be happening?

There’s a hurricane coming through soon so idk now LOL
In any case, expect it after you see us releasing Wilder Wild 3.0 and Trailier Tales, as those are both our priority at the moment

**Comment by AViewFromTheTop** [comment]
Does this happen in the latest release?

**Comment by ExDrill** [comment]
Sorry for the late response, I'll check this out soon.

**Comment by ExDrill** [comment]
Reinstalled Simple Copper Pipes with the new update and haven't experienced this issue by trying to do the same conditions for it. Looks like it was fixed! :D

**Comment by AViewFromTheTop** [comment]
Poggggg
