### ISSUE TITLE
[Crash] Simple Copper Pipes 2.0.1 and Create Fabric 0.5.1-f-build.1417

### ISSUE THREAD

**Issue by MrBeat93** [AViewFromTheTop/SimpleCopperPipesMC#47]
Minecraft: `1.20.1`
Create Fabric: `0.5.1-f-build.1417+mc1.20.1.jar`
Fabric API: `0.92.2+1.20.11.jar`
Simple Copper Pipes: `SimpleCopperPipes-mc1.20.1-2.0.11.jar`

The game wont start with the lastest `SimpleCopperPipes-mc1.20.1-2.0.11.jar` update
https://mclo.gs/vatuYFn

I made a new instance with the only required mods to make it easier

**Comment by AViewFromTheTop** [comment]
This has been fixed in release 2.0.2
