### ISSUE TITLE
pipe stops working when there is a large amount of items

### ISSUE THREAD

**Issue by IceCola97** [AViewFromTheTop/SimpleCopperPipesMC#51]
When the pipe is filled, it will not transfer to the next container even after the next container is emptied.
This bug was reproduced by me in 1.21.1-fabric,ensuring that only this one mod is present, with the structure as follows:
![IMG_20241128_100404.jpg](https://github.com/user-attachments/assets/2ab113f0-1584-42ce-bc10-43c4150bd501)
(before emptied, every container was full)
The hopper circled in the image, after being emptied, will not have the pipe transfer items to it.
Moreover, it's not just the transfer to the hopper; in my bamboo farm, there are similar situations at the pipe-to-pipe transfer points at the turns.

**Comment by AViewFromTheTop** [comment]
I'm unable to reproduce this.

**Comment by AViewFromTheTop** [comment]
nvm

**Comment by AViewFromTheTop** [comment]
Good news for you!
@Treetrain1 has fixed this issue, and I will be making a release shortly for 1.21, 1.21.2, and 1.21.4 with the fix.

**Comment by IceCola97** [comment]
Thanks for the fix😘
