### ISSUE TITLE
Some ideas I had

### ISSUE THREAD

**Issue by faelBrunnoS** [AViewFromTheTop/SimpleCopperPipesMC#9]
### L and T Tubes
Could you add L and T tubes?
With L-tubes or T-tubes in just 1 block, it would remove the need for multiple tubes for what was sometimes supposed to be a "simple" system.

But as the T-Tube would have one input and two outputs, the filter function must exist to work.
The GUI could be something like this:
![image](https://user-images.githubusercontent.com/83606488/198740796-bdb0f5d7-5226-4eee-a98f-b3b971a175b3.png)
If ALL is selected, it will take them all and send them to that output and will disable the filter for that output.
If ALL is not selected, it will activate the filter and you will select which blocks or items will go to that exit.

Output 1 should always be the output closest to the input, and Output 2 the furthest. (For easy identification).

Therefore, if all are marked as ALL, Out-1 will always have priority and will receive all items and blocks.
But if Out-2 for example has not selected ALL but Out-1 has, then the priority would be Out-2 and only then Out-1 would receive the items.

_It could have some very discreet arrow on the texture to indicate the direction of the tube._

### Redstone ON/OFF
A different tube from the normal ones in which when triggered by redstone, it would not pull the items.
For example: You put him in the chest and only when you turn on a lever he would start pulling the items.

### Item Filtering
Filtering items would be an awesome feature for this mod. Something like [Copper Hopper](https://www.curseforge.com/minecraft/mc-mods/copper-hopper) would be nice, without overdone filters (some add 27 filters).

In [Copper Hopper](https://www.curseforge.com/minecraft/mc-mods/copper-hopper) it is possible to filter only 5 items.
But it only sends the items that are in the filter. It could be something like this. (I will give an example in image on how I would use such a system)

### Mute Tube
An option to mute the tube would be great.
Because it's not always nice to hear the tube working because sometimes there's a lot of tube pulling at the same time and it becomes a zone.

### Image Example
**Example with current tubes**
![image](https://user-images.githubusercontent.com/83606488/198742335-788d41c2-fef7-4fd5-a4f4-82d39b8a9ec3.png)

**Example with tubes of ideas** (edited image)
![image](https://user-images.githubusercontent.com/83606488/198745418-31e5166f-2ead-422a-8042-31f1059c7bc8.png)
That way, you would have a lot less tubes in use!
It would look better visually and take up less space.
Helping both the system and the server (if multiplayer)!

## Conclusion
All the images were edited in a raw way, I just did this so you can better understand what I thought.
If you need any references, I thought of these:

**Filter System**: [Copper Hopper](https://www.curseforge.com/minecraft/mc-mods/copper-hopper)
**T and L System**: [SimpleTransport for Fabric](https://www.curseforge.com/minecraft/mc-mods/simpletransport-for-fabric)
**Multi-Directional Hopper**: [PneumaticCraft: Repressurized](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized)

**Comment by AViewFromTheTop** [comment]
Those sorts of tubes would require a tremendous amount of work in terms of models, textures, lang, tags, etc., on top of removing Minecraft's nuance of having to manager your block placement carefully if you want to make contraptions.
Unfortunately I will have to decline this for those two reasons, though I am open to someone else making an extension of the mod that adds them.
